[package]
name = "File-duplicate-checker"
version = "0.1.0"
authors = ["KunoiSayami <46131041+KunoiSayami@users.noreply.github.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
sha2 = "0.9.1"
tokio = { version = "0.3", features = ["full"] }
rusqlite = "0.24.1"