[package]
name = "file_duplicate_checker"
version = "0.1.0"
authors = ["KunoiSayami <46131041+KunoiSayami@users.noreply.github.com>"]
edition = "2018"

[dependencies]
sha2 = "0.9.1"

[dependencies.rusqlite]
version = "0.24.1"
features = ["bundled"]