[package]
name = "File-duplicate-checker"
version = "0.1.0"
authors = ["KunoiSayami <46131041+KunoiSayami@users.noreply.github.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
sha2 = "0.9.1"

[dependencies.rusqlite]
version = "0.24.1"
features = ["bundled"]