name: Build binary

on:
  push:
    tags:
      - v**
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        job:
          - { os: macos-latest }
          - { os: ubuntu-latest }
          - { os: windows-latest }


    name: Build
    runs-on: ${{ matrix.job.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Update rust
        run: rustup update
      - name: Build binary
        run: cargo build --release
      - name: Rename binary
        id: rename
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            BIN='file_duplicate_checker_linux_amd64'
            mv target/release/file_duplicate_checker target/release/$BIN
          elif [ "$RUNNER_OS" == "macOS" ]; then
            BIN='file_duplicate_checker_darwin_amd64'
            mv target/release/file_duplicate_checker target/release/$BIN
          else
            BIN='file_duplicate_checker_windows_amd64.exe'
            mv target/release/file_duplicate_checker.exe target/release/$BIN
          fi
          if [[ $GITHUB_REF == *"beta"* ]]; then
            PREREPELASE=true
          else
            PREREPELASE=false
          fi
          echo "bin=target/release/$BIN" >> $GITHUB_OUTPUT
          #echo "prerelease=$PREREPELASE" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            target/release/file_duplicate_checker_*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        #with:
        #  files: ${{ steps.rename.outputs.bin }}
        #  prerelease: fromJSON(steps.rename.outputs.prerelease)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup target install aarch64-unknown-linux-musl
      - run: cargo install cross
      - name: Build binary
        run: cross build --release --target aarch64-unknown-linux-musl
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-musl
          override: true
      - name: Build aarch 64 binary
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release
      - run: mv target/aarch64-unknown-linux-musl/release/file_duplicate_checker target/aarch64-unknown-linux-musl/release/file_duplicate_checker_linux_aarch64
      - name: Check is pre-release
        id: prerelasecheck
        shell: bash
        run: |
          if [[ $GITHUB_REF == *"beta"* ]]; then
            PREREPELASE=true
          else
            PREREPELASE=false
          fi
          echo "bin=target/release/$BIN" >> $GITHUB_OUTPUT
          #echo "::set-output prerelease=$PREREPELASE"
      - uses: actions/upload-artifact@v2
        with:
          name: aarch64-artifact
          path: target/aarch64-unknown-linux-musl/release/file_duplicate_checker_linux_aarch64
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        #with:
        #  files: target/aarch64-unknown-linux-musl/release/file_duplicate_checker_linux_aarch64
        #  prerelease: fromJSON(steps.prerelasecheck.outputs.prerelease)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}